#!/bin/bash

HOST_IP=10.211.55.54
HOST_IP_ETH1=10.211.55.54
NETWORK_IP=xxxxxx
NETWORK_IP_ETH1=xxxxxx
NETWORK_IP_ETH2=xxxxxx
COMPUTE_IP=xxxxxx
COMPUTE_IP_ETH1=xxxxxx

MYSQL_PASSWORD=swordfish

DEBUG_OPEN=True

VERBOSE_OPEN=True

export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=swordfish
export OS_AUTH_URL="http://Control-eth1:5000/v2.0/"
export OS_SERVICE_ENDPOINT="http://10.211.55.54:35357/v2.0"
export OS_SERVICE_TOKEN=swordfish
