#!/bin/bash

source ../openrc

echo ''
echo 'Dropping databases ...'
echo ''

mysql -u root -p$MYSQL_PASSWORD <<EOF
DROP DATABASE nova;
DROP DATABASE cinder;
DROP DATABASE glance;
DROP DATABASE keystone;
DROP DATABASE neutron;
DROP DATABASE heat;
EOF

echo ''
echo 'Creating databases ...'
echo ''

mysql -u root -p$MYSQL_PASSWORD <<EOF
CREATE DATABASE nova;
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'$CONTROL_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'$NETWORK_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'$COMPUTE_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE DATABASE cinder;
GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'$CONTROL_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'$NETWORK_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'$COMPUTE_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE DATABASE glance;
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'$CONTROL_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'$NETWORK_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'$COMPUTE_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE DATABASE keystone;
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'$CONTROL_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'$NETWORK_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'$COMPUTE_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE DATABASE neutron;
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'$CONTROL_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'$NETWORK_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'$COMPUTE_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE DATABASE heat;
GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'$CONTROL_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'$NETWORK_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'$COMPUTE_HOST_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
FLUSH PRIVILEGES;
EOF

echo ''
echo 'Getting list of databases ...'
echo ''

mysql -u root -p$MYSQL_PASSWORD <<EOF
show databases;
EOF
